#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base
WORKDIR /app
EXPOSE 81
ENV ASPNETCORE_URLS=http://*:81

FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build
WORKDIR /src
COPY ["ServerApi/ServerApi.csproj", "ServerApi/"]
RUN dotnet restore "ServerApi/ServerApi.csproj"
COPY . .
WORKDIR "/src/ServerApi"
RUN dotnet build "ServerApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ServerApi.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ServerApi.dll"]